### ISSUE TITLE
StrawberrySetup false-positive

### ISSUE THREAD

**Issue by jonaski** [The-DFIR-Report/Yara-Rules#3]
StrawberrySetup-1.0.7-mingw-x64.exe:
https://www.virustotal.com/gui/file/b351c45c0b2b0b8285e1562ed4c6f8f6072aa8619e83f6e201aae6cf2654cbc5

```
Matches rule case_4485_ekix4 by The DFIR Report from ruleset IcedID and Cobalt Strike vs Antivirus at https://github.com/The-DFIR-Report/Yara-Rules
  4485 - file ekix4.dll
```

Setup file can be downloaded here: https://files.strawberrymusicplayer.org/StrawberrySetup-1.0.7-mingw-x64.exe

All generated MinGW-W64 based setups have this issue: https://builds.strawberrymusicplayer.org/windows/

These are NSIS based setups generated using makensis cross-built on openSUSE here: https://build.opensuse.org/package/show/windows:mingw:win32/mingw32-cross-nsis

We also have a MSVC (Visual Studio 2019) compiled version, this one does not trigger.

**Comment by The-DFIR-Report** [comment]
Upon downloading the reported file we cannot trigger a match for the reported file and the ruleset. What tool were you using with the rules that triggered the finding?

**Comment by jonaski** [comment]
I was not using any tool. VirusTotal pointed to this repository as you can see in the above text. It's since removed.
